version: '3'
services:
#  liferay:
#    build: ./LIFERAY/
#    ports:
#    - "8080:8080"
#    volumes:
#    - ./LIFERAY/prueba:/liferay
#  liferayossi:
#    build: ./LIFERAY_OSSI/
#    ports:
#    - "8073:8080"
#    volumes:
#    - ./LIFERAY_OSSI/liferay-portal-6.1.0-ce-ga1:/liferay
#    - /home/ivan/Documentos/DOCKER_DEV_L7/data/data:/liferay/data
  oracle:
    image: ivancondori/oracle-11g:11.2.0.4_PE
    hostname: oracle-docker
    ports: 
    - "1521:1521"
    volumes:
    - ./oracle/app:/opt/oracle/app
    - ./oracle/dpdump:/opt/oracle/dpdump
    - ./oracle/install:/install
    privileged: true

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ADVERTISED_HOST_NAME=10.75.23.249
#  mysql:
#    image: quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
#    ports:
#     - 3306:3306
#    environment:
#     - MYSQL_ROOT_PASSWORD=debezium
#     - MYSQL_USER=mysqluser
#     - MYSQL_PASSWORD=mysqlpw 
  postgres:
    image: quay.io/debezium/postgres:9.6
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=inventory
  connect:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    build:
      context: debezium-jdbc-es
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - oracle
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
     - LD_LIBRARY_PATH=/instant_client

